### ISSUE TITLE
Adding file commands like MV to FogOS

### ISSUE THREAD

**Issue by AlexBareli** [USF-OS/FogOS#16]
I would like to add the ability to move files to new directories since it is something that is missing from FogOS. Let me know how I should approach this, or if a command like copy or pwd will be easier.

**Comment by malensek** [comment]
This would be okay if you implement all 3 of `mv`, `cp`, and `pwd`. My rationale is all 3 are pretty easy to implement:
* `mv`: link + unlink system calls (we can chat about this if you want because we haven't learned about link/unlink yet)
* `cp`: read + write system calls
* `pwd`: add a system call to get the CWD of a process, pass buffer to system call and have it populate it, print buffer

If you don't want all 3 (just the basics) then maybe you can research some extra flags to support for these.
