### ISSUE TITLE
Project 1 - String library features

### ISSUE THREAD

**Issue by Jsk07211** [USF-OS/FogOS#3]
Writing strncmp(), strncat(), strncpy(), strstr(), strtok() :)

By Jaz Ku and Emmanuel Wang

**Comment by malensek** [comment]
I think this would be reasonable as long as you add
* strspn
* strcspn (opposite of strspn, so pretty easy)
* strsep (subtly different than strtok)
* strtok_r (strtok without issues with reentrancy, multi threads... really just passing in an extra variable instead of using a static global.)

My logic is that strncmp, strncat, strncpy are all very similar to what we already have in ulib.c.

**Comment by Jsk07211** [comment]
Can we do atoi() and scanf() while we're at it or no :') It'll be fun :D

**Comment by malensek** [comment]
Limited scanf sounds like fun. 👍 :-)
